server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: latest
      group-id: fitness
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value_deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    urls:
      - name: program-v1
        url: spec-program-v1.yml

database:
  url: jdbc:postgresql://localhost:5432/fitness
  user: postgres
  password: postgres
  schema: public